services:
  crew:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env3
    command: bash -lc "pip install -r requirements.txt && python run.py 'feature: lisää kirjautumissivu'"
  
  crew-invest:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env3
    command: bash -lc "pip install -r requirements.txt && python run_idea.py 'brief: EU data center REITit hyötyvät AI‑kysynnästä'"