global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'hybrid_bot'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9108']   # tai <host-ip>:9108 / Docker-porttimappaus
    metrics_path: /metrics
    scheme: http
